development:
  adapter: postgresql
  database: grapevine_development
  pool: 5
  timeout: 5000
  encoding: unicode

production:
  adapter: postgresql
  database: grapevine_production
  pool: 5
  timeout: 5000
  encoding: unicode
